name: Analyze with SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: unosquare/bump-nuget-version/.github/workflows/build-true.yml@master
    with:
      sln-file: "Unosquare.DateTimeExt.sln"
      sonar-key: "unosquare_unodatetime"
    secrets:
      github-token: ${{ secrets.GPR_ACCESS_TOKEN }}
      cache-version: ${{ secrets.CACHE_VERSION }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
