name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🛎 Checkout
      uses: actions/checkout@v4
    - name: 📦 Cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ secrets.cache-version }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-${{ secrets.cache-version }}-
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Build and test
      run: |
        dotnet build -c Release
        dotnet test
